// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: buyers.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createBuyer = `-- name: CreateBuyer :one
INSERT INTO buyers (name, email, user_id)
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, deleted_at, name, email, user_id
`

type CreateBuyerParams struct {
	Name   string
	Email  string
	UserID uuid.UUID
}

func (q *Queries) CreateBuyer(ctx context.Context, arg CreateBuyerParams) (Buyer, error) {
	row := q.db.QueryRowContext(ctx, createBuyer, arg.Name, arg.Email, arg.UserID)
	var i Buyer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Email,
		&i.UserID,
	)
	return i, err
}

const getBuyerByID = `-- name: GetBuyerByID :one
SELECT id, created_at, updated_at, deleted_at, name, email, user_id FROM buyers
WHERE id = $1
`

func (q *Queries) GetBuyerByID(ctx context.Context, id uuid.UUID) (Buyer, error) {
	row := q.db.QueryRowContext(ctx, getBuyerByID, id)
	var i Buyer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Email,
		&i.UserID,
	)
	return i, err
}

const getBuyers = `-- name: GetBuyers :many
SELECT id, created_at, updated_at, deleted_at, name, email, user_id FROM buyers
WHERE deleted_at IS NULL
AND user_id = $1
`

func (q *Queries) GetBuyers(ctx context.Context, userID uuid.UUID) ([]Buyer, error) {
	rows, err := q.db.QueryContext(ctx, getBuyers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Buyer
	for rows.Next() {
		var i Buyer
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.Email,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIDForBuyer = `-- name: GetUserIDForBuyer :one
SELECT user_id FROM buyers
WHERE id = $1
`

func (q *Queries) GetUserIDForBuyer(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUserIDForBuyer, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const restoreBuyer = `-- name: RestoreBuyer :one
UPDATE buyers
SET updated_at = NOW(), deleted_at = NULL
WHERE id = $1
RETURNING id, created_at, updated_at, deleted_at, name, email, user_id
`

func (q *Queries) RestoreBuyer(ctx context.Context, id uuid.UUID) (Buyer, error) {
	row := q.db.QueryRowContext(ctx, restoreBuyer, id)
	var i Buyer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Email,
		&i.UserID,
	)
	return i, err
}

const softDeleteBuyer = `-- name: SoftDeleteBuyer :one
UPDATE buyers
SET updated_at = NOW(), deleted_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, deleted_at, name, email, user_id
`

func (q *Queries) SoftDeleteBuyer(ctx context.Context, id uuid.UUID) (Buyer, error) {
	row := q.db.QueryRowContext(ctx, softDeleteBuyer, id)
	var i Buyer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Email,
		&i.UserID,
	)
	return i, err
}

const updateBuyerEmail = `-- name: UpdateBuyerEmail :one
UPDATE buyers
SET updated_at = NOW(), email = $1
WHERE id = $2
RETURNING id, created_at, updated_at, deleted_at, name, email, user_id
`

type UpdateBuyerEmailParams struct {
	Email string
	ID    uuid.UUID
}

func (q *Queries) UpdateBuyerEmail(ctx context.Context, arg UpdateBuyerEmailParams) (Buyer, error) {
	row := q.db.QueryRowContext(ctx, updateBuyerEmail, arg.Email, arg.ID)
	var i Buyer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Email,
		&i.UserID,
	)
	return i, err
}

const updateBuyerName = `-- name: UpdateBuyerName :one
UPDATE buyers
SET updated_at = NOW(), name = $1
WHERE id = $2
RETURNING id, created_at, updated_at, deleted_at, name, email, user_id
`

type UpdateBuyerNameParams struct {
	Name string
	ID   uuid.UUID
}

func (q *Queries) UpdateBuyerName(ctx context.Context, arg UpdateBuyerNameParams) (Buyer, error) {
	row := q.db.QueryRowContext(ctx, updateBuyerName, arg.Name, arg.ID)
	var i Buyer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Email,
		&i.UserID,
	)
	return i, err
}
