// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/huangmatty/crumbs/internal/psql_types"
)

type Buyer struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
	Name         string
	Email        sql.NullString
	PhoneNumbers []psql_types.Phone
	UserID       uuid.UUID
}

type Offer struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  sql.NullTime
	Gaurantees []psql_types.Money
	UserID     uuid.UUID
}

type OffersBuyer struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	OfferID   uuid.NullUUID
	BuyerID   uuid.NullUUID
}

type OffersTalent struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	OfferID   uuid.NullUUID
	TalentID  uuid.NullUUID
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	UserID    uuid.UUID
}

type Talent struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	Name      string
	Email     sql.NullString
	UserID    uuid.UUID
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      sql.NullTime
	Username       string
	Email          string
	HashedPassword string
}
