// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: offers.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOffer = `-- name: CreateOffer :one
INSERT INTO offers (start_date, end_date, buyer_id, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, updated_at, deleted_at, start_date, end_date, buyer_id, user_id
`

type CreateOfferParams struct {
	StartDate sql.NullTime
	EndDate   sql.NullTime
	BuyerID   uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) CreateOffer(ctx context.Context, arg CreateOfferParams) (Offer, error) {
	row := q.db.QueryRowContext(ctx, createOffer,
		arg.StartDate,
		arg.EndDate,
		arg.BuyerID,
		arg.UserID,
	)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.StartDate,
		&i.EndDate,
		&i.BuyerID,
		&i.UserID,
	)
	return i, err
}

const getOfferByID = `-- name: GetOfferByID :one
SELECT id, created_at, updated_at, deleted_at, start_date, end_date, buyer_id, user_id FROM offers
WHERE id = $1
`

func (q *Queries) GetOfferByID(ctx context.Context, id uuid.UUID) (Offer, error) {
	row := q.db.QueryRowContext(ctx, getOfferByID, id)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.StartDate,
		&i.EndDate,
		&i.BuyerID,
		&i.UserID,
	)
	return i, err
}

const getOffers = `-- name: GetOffers :many
SELECT id, created_at, updated_at, deleted_at, start_date, end_date, buyer_id, user_id FROM offers
WHERE deleted_at IS NULL
AND user_id = $1
`

func (q *Queries) GetOffers(ctx context.Context, userID uuid.UUID) ([]Offer, error) {
	rows, err := q.db.QueryContext(ctx, getOffers, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Offer
	for rows.Next() {
		var i Offer
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.StartDate,
			&i.EndDate,
			&i.BuyerID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIDForOffer = `-- name: GetUserIDForOffer :one
SELECT user_id FROM offers
WHERE id = $1
`

func (q *Queries) GetUserIDForOffer(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getUserIDForOffer, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const restoreOffer = `-- name: RestoreOffer :one
UPDATE offers
SET updated_at = NOW(), deleted_at = NULL
WHERE id = $1
RETURNING id, created_at, updated_at, deleted_at, start_date, end_date, buyer_id, user_id
`

func (q *Queries) RestoreOffer(ctx context.Context, id uuid.UUID) (Offer, error) {
	row := q.db.QueryRowContext(ctx, restoreOffer, id)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.StartDate,
		&i.EndDate,
		&i.BuyerID,
		&i.UserID,
	)
	return i, err
}

const softDeleteOffer = `-- name: SoftDeleteOffer :one
UPDATE offers
SET updated_at = NOW(), deleted_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, deleted_at, start_date, end_date, buyer_id, user_id
`

func (q *Queries) SoftDeleteOffer(ctx context.Context, id uuid.UUID) (Offer, error) {
	row := q.db.QueryRowContext(ctx, softDeleteOffer, id)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.StartDate,
		&i.EndDate,
		&i.BuyerID,
		&i.UserID,
	)
	return i, err
}

const updateOfferEndDate = `-- name: UpdateOfferEndDate :one
UPDATE offers
SET updated_at = NOW(), end_date = $1
WHERE id = $2
RETURNING id, created_at, updated_at, deleted_at, start_date, end_date, buyer_id, user_id
`

type UpdateOfferEndDateParams struct {
	EndDate sql.NullTime
	ID      uuid.UUID
}

func (q *Queries) UpdateOfferEndDate(ctx context.Context, arg UpdateOfferEndDateParams) (Offer, error) {
	row := q.db.QueryRowContext(ctx, updateOfferEndDate, arg.EndDate, arg.ID)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.StartDate,
		&i.EndDate,
		&i.BuyerID,
		&i.UserID,
	)
	return i, err
}

const updateOfferStartDate = `-- name: UpdateOfferStartDate :one
UPDATE offers
SET updated_at = NOW(), start_date = $1
WHERE id = $2
RETURNING id, created_at, updated_at, deleted_at, start_date, end_date, buyer_id, user_id
`

type UpdateOfferStartDateParams struct {
	StartDate sql.NullTime
	ID        uuid.UUID
}

func (q *Queries) UpdateOfferStartDate(ctx context.Context, arg UpdateOfferStartDateParams) (Offer, error) {
	row := q.db.QueryRowContext(ctx, updateOfferStartDate, arg.StartDate, arg.ID)
	var i Offer
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.StartDate,
		&i.EndDate,
		&i.BuyerID,
		&i.UserID,
	)
	return i, err
}
