// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: talents.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTalent = `-- name: CreateTalent :one
INSERT INTO talents (name, email, user_id)
VALUES ($1, $2, $3)
RETURNING id, created_at, updated_at, deleted_at, name, email, user_id
`

type CreateTalentParams struct {
	Name   string
	Email  sql.NullString
	UserID uuid.UUID
}

func (q *Queries) CreateTalent(ctx context.Context, arg CreateTalentParams) (Talent, error) {
	row := q.db.QueryRowContext(ctx, createTalent, arg.Name, arg.Email, arg.UserID)
	var i Talent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Email,
		&i.UserID,
	)
	return i, err
}

const getTalentByID = `-- name: GetTalentByID :one
SELECT id, created_at, updated_at, deleted_at, name, email, user_id FROM talents
WHERE id = $1
`

func (q *Queries) GetTalentByID(ctx context.Context, id uuid.UUID) (Talent, error) {
	row := q.db.QueryRowContext(ctx, getTalentByID, id)
	var i Talent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Email,
		&i.UserID,
	)
	return i, err
}

const getTalents = `-- name: GetTalents :many
SELECT id, created_at, updated_at, deleted_at, name, email, user_id FROM talents
WHERE deleted_at IS NULL
AND user_id = $1
ORDER BY name
`

func (q *Queries) GetTalents(ctx context.Context, userID uuid.UUID) ([]Talent, error) {
	rows, err := q.db.QueryContext(ctx, getTalents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Talent
	for rows.Next() {
		var i Talent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Name,
			&i.Email,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTalent = `-- name: SoftDeleteTalent :one
UPDATE talents
SET updated_at = NOW(), deleted_at = NOW()
WHERE id = $1
RETURNING id, created_at, updated_at, deleted_at, name, email, user_id
`

func (q *Queries) SoftDeleteTalent(ctx context.Context, id uuid.UUID) (Talent, error) {
	row := q.db.QueryRowContext(ctx, softDeleteTalent, id)
	var i Talent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Email,
		&i.UserID,
	)
	return i, err
}

const updateTalentEmail = `-- name: UpdateTalentEmail :one
UPDATE talents
SET updated_at = NOW(), email = $1
WHERE id = $2
RETURNING id, created_at, updated_at, deleted_at, name, email, user_id
`

type UpdateTalentEmailParams struct {
	Email sql.NullString
	ID    uuid.UUID
}

func (q *Queries) UpdateTalentEmail(ctx context.Context, arg UpdateTalentEmailParams) (Talent, error) {
	row := q.db.QueryRowContext(ctx, updateTalentEmail, arg.Email, arg.ID)
	var i Talent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Email,
		&i.UserID,
	)
	return i, err
}

const updateTalentName = `-- name: UpdateTalentName :one
UPDATE talents
SET updated_at = NOW(), name = $1
WHERE id = $2
RETURNING id, created_at, updated_at, deleted_at, name, email, user_id
`

type UpdateTalentNameParams struct {
	Name string
	ID   uuid.UUID
}

func (q *Queries) UpdateTalentName(ctx context.Context, arg UpdateTalentNameParams) (Talent, error) {
	row := q.db.QueryRowContext(ctx, updateTalentName, arg.Name, arg.ID)
	var i Talent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Email,
		&i.UserID,
	)
	return i, err
}
