// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: talents.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTalent = `-- name: CreateTalent :one
INSERT INTO talents (name, user_id)
VALUES ($1, $2)
RETURNING id, created_at, updated_at, deleted_at, name, email, user_id
`

type CreateTalentParams struct {
	Name   string
	UserID uuid.UUID
}

func (q *Queries) CreateTalent(ctx context.Context, arg CreateTalentParams) (Talent, error) {
	row := q.db.QueryRowContext(ctx, createTalent, arg.Name, arg.UserID)
	var i Talent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Name,
		&i.Email,
		&i.UserID,
	)
	return i, err
}
